[build]
  publish = "caixa-de-reclamacoes-da-turma/public"
  command = ""

[[redirects]]
  from = "/enviar"
  to = "https://caixa-reclamacoes-turma.onrender.com/enviar"
  status = 200
  force = true

[[redirects]]
  from = "/admin-data"
  to = "https://caixa-reclamacoes-turma.onrender.com/admin-data"
  status = 200
  force = true

[[redirects]]
  from = "/admin-delete/*"
  to = "https://caixa-reclamacoes-turma.onrender.com/admin-delete/:splat"
  status = 200
  force = true
